### ISSUE TITLE
Puppet 4 and Above Use /etc/puppetlabs/code/hiera.yaml as the default location for hiera.yaml

### ISSUE THREAD

**Issue by npwalker** [hunner/puppet-hiera#97]
This means that the symlink should be from `/etc/puppetlabs/code/hiera.yaml` instead of `/etc/hiera.yaml` in Puppet 4 and above.

**Comment by hunner** [comment]
The `/etc/hiera.yaml` symlink is just for the hiera command line tool. It does appear that the new version of `hiera` uses `/etc/puppetlabs/code/hiera.yaml` but as this file is an actual file there is no need for a symlink at all.

On the other hand, I don't know if it's guaranteed to have a new version of the hiera cli tool just because puppet is version 4; do you know?

**Comment by npwalker** [comment]
"we’ve gone to an All-In-One package (which we refer to as “AIO”, like a bad hand in Words With Friends), which includes Puppet 4, both Facter 2.4 and CFacter 0.4, the latest Hiera and Mcollective, as well Ruby 2.1.5, OpenSSL 1.0.0r, and our gem dependencies. "

From here: https://docs.puppetlabs.com/puppet/4.0/reference/release_notes.html#all-in-one-packaging

So, I think puppet 4 = AIO which means that hiera 3 is already in there.

**Comment by jyaworski** [comment]
I believe this has been solved. Can you confirm?
